//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarEquipment()
        {
            this.Car = new HashSet<Car>();
            this.CarGroupAttribute = new HashSet<CarGroupAttribute>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BodyID { get; set; }
        public Nullable<int> TransmissionID { get; set; }
        public Nullable<int> SteeringWheelPositionID { get; set; }
        public int EngineCapacity { get; set; }
        public int EnginePower { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> EngineID { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public Nullable<decimal> Acceleration { get; set; }
        public Nullable<int> DriveID { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Car { get; set; }
        public virtual CarBody CarBody { get; set; }
        public virtual CarDrive CarDrive { get; set; }
        public virtual CarEngine CarEngine { get; set; }
        public virtual CarFuel CarFuel { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual CarSteeringWheelPosition CarSteeringWheelPosition { get; set; }
        public virtual CarTransmission CarTransmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarGroupAttribute> CarGroupAttribute { get; set; }
    }
}
