//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class CounteragentInteraction
    {
        public int ID { get; set; }
        public Nullable<int> CounteragentID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public System.DateTime ContactDate { get; set; }
        public string Comment { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Counteragent Counteragent { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual CounteragentInteractionType CounteragentInteractionType { get; set; }
    }
}
