//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class CounteragentContactPerson
    {
        public int ID { get; set; }
        public Nullable<int> CounteragentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> PostID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Counteragent Counteragent { get; set; }
        public virtual StaffPost StaffPost { get; set; }
        public virtual StaffRole StaffRole { get; set; }
    }
}
