//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class Log
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual LogLevel LogLevel { get; set; }
        public virtual LogType LogType { get; set; }
        public virtual User User { get; set; }
    }
}
