//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductArrivalPosition = new HashSet<ProductArrivalPosition>();
            this.ProductOrderPosition = new HashSet<ProductOrderPosition>();
            this.ProductSpecific = new HashSet<ProductSpecific>();
            this.ProductSuitableCarBrand = new HashSet<ProductSuitableCarBrand>();
            this.ProductSuitableCarModel = new HashSet<ProductSuitableCarModel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<long> Article { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SalePrice { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> UnitOfMeasurementID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<decimal> Allowance { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductArrivalPosition> ProductArrivalPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderPosition> ProductOrderPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSpecific> ProductSpecific { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSuitableCarBrand> ProductSuitableCarBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSuitableCarModel> ProductSuitableCarModel { get; set; }
    }
}
