//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class ProductOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrder()
        {
            this.ProductOrderPosition = new HashSet<ProductOrderPosition>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CounteragentID { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Counteragent Counteragent { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderPosition> ProductOrderPosition { get; set; }
    }
}
