//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SADAEntities : DbContext
    {
        public SADAEntities()
            : base("name=SADAEntities")
        {
            Database.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarAttribute> CarAttribute { get; set; }
        public virtual DbSet<CarBody> CarBody { get; set; }
        public virtual DbSet<CarBrand> CarBrand { get; set; }
        public virtual DbSet<CarColor> CarColor { get; set; }
        public virtual DbSet<CarDealership> CarDealership { get; set; }
        public virtual DbSet<CarDrive> CarDrive { get; set; }
        public virtual DbSet<CarEngine> CarEngine { get; set; }
        public virtual DbSet<CarEquipment> CarEquipment { get; set; }
        public virtual DbSet<CarEquipmentGroupAttribute> CarEquipmentGroupAttribute { get; set; }
        public virtual DbSet<CarExpense> CarExpense { get; set; }
        public virtual DbSet<CarFuel> CarFuel { get; set; }
        public virtual DbSet<CarFuelType> CarFuelType { get; set; }
        public virtual DbSet<CarGroupAttribute> CarGroupAttribute { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<CarPaymentFromCounteragent> CarPaymentFromCounteragent { get; set; }
        public virtual DbSet<CarPaymentToCounteragent> CarPaymentToCounteragent { get; set; }
        public virtual DbSet<CarPhoto> CarPhoto { get; set; }
        public virtual DbSet<CarStatus> CarStatus { get; set; }
        public virtual DbSet<CarSteeringWheelPosition> CarSteeringWheelPosition { get; set; }
        public virtual DbSet<CarTransmission> CarTransmission { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Counteragent> Counteragent { get; set; }
        public virtual DbSet<CounteragentContactPerson> CounteragentContactPerson { get; set; }
        public virtual DbSet<CounteragentGroup> CounteragentGroup { get; set; }
        public virtual DbSet<CounteragentInteraction> CounteragentInteraction { get; set; }
        public virtual DbSet<CounteragentInteractionType> CounteragentInteractionType { get; set; }
        public virtual DbSet<CounteragentType> CounteragentType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<ExpenseGroup> ExpenseGroup { get; set; }
        public virtual DbSet<ExpenseType> ExpenseType { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<IndividualPerson> IndividualPerson { get; set; }
        public virtual DbSet<JuridicalPerson> JuridicalPerson { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogLevel> LogLevel { get; set; }
        public virtual DbSet<LogType> LogType { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PassportGiver> PassportGiver { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductArrival> ProductArrival { get; set; }
        public virtual DbSet<ProductArrivalPosition> ProductArrivalPosition { get; set; }
        public virtual DbSet<ProductGroup> ProductGroup { get; set; }
        public virtual DbSet<ProductOrder> ProductOrder { get; set; }
        public virtual DbSet<ProductOrderPosition> ProductOrderPosition { get; set; }
        public virtual DbSet<ProductSpecific> ProductSpecific { get; set; }
        public virtual DbSet<ProductSuitableCarBrand> ProductSuitableCarBrand { get; set; }
        public virtual DbSet<ProductSuitableCarModel> ProductSuitableCarModel { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<SalaryType> SalaryType { get; set; }
        public virtual DbSet<SoloTrader> SoloTrader { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffPost> StaffPost { get; set; }
        public virtual DbSet<StaffRole> StaffRole { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<TableClassification> TableClassification { get; set; }
        public virtual DbSet<TableClassificationType> TableClassificationType { get; set; }
        public virtual DbSet<TaxationSystemType> TaxationSystemType { get; set; }
        public virtual DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRoleRight> UserRoleRight { get; set; }
    }
}
